---
hosts: 
  - name: localhost
    desc: ""
    inv: "Demo Inventory"
    vars: {}

# Namespace for demo components
demo_components_namespace: "demo-components"

# Alternative namespaces (add all namespaces that ArgoCD will have to manage)
demo_alternative_namespaces:
  - openshift-operators
  - watches-eshop

# External images - for Image Streams
demo_external_images:
  - name: gitea
    image: quay.io/gpte-devops-automation/gitea
    version: 1.16

# External repositories
demo_external_repositories:
  - name: quarkus-app
    url: https://github.com/clbartolome/quarkus-app

# Components
demo_components:
  - name: openshift-pipelines
    argo_path: deploy
  - name: watches-eshop
    argo_path: app-sets